# Generated by Django 4.2 on 2026-07-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('bodeguero', 'Bodeguero')], default='cliente', max_length=20),
        ),
    ]
